name: Build and Publish to PyPI

on:
  push:
    branches:
      - master  # 每次 push 到 master 时触发构建和发布

permissions:
  contents: read
  id-token: write  # Trusted Publisher 所需

jobs:
  build-and-publish:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]

    env:
      CIBW_BUILD: "cp310-*"
      CIBW_SKIP: "*-win32 *-manylinux_i686 *-musllinux* pp*"
      CIBW_BUILD_VERBOSITY: "1"

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"  # 仅用于运行 cibuildwheel 自身，不影响构建目标版本

      - name: Install build tools
        run: |
          pip install --upgrade pip
          pip install cibuildwheel==2.16.5 wheel

      - name: Build wheels for Python 3.10
        run: cibuildwheel --output-dir dist

      - name: Publish to PyPI via Trusted Publisher
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages: dist/*
