name: Build and Publish to PyPI

on:
  release:
    types: [ published ]

permissions:
  contents: read
  id-token: write

jobs:
  build-and-publish:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]

    env:
      CIBW_BUILD: "cp310-*"
      CIBW_SKIP: "*-win32 *-manylinux_i686 *-musllinux* pp*"

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"  # For running cibuildwheel

      - name: Install cibuildwheel
        run: pip install cibuildwheel==2.16.5

      - name: Build wheels (Python 3.10 only)
        run: cibuildwheel --output-dir dist

      - name: Publish to PyPI via Trusted Publisher
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages: dist/*
