name: Build and Publish to PyPI

on:
  push:
    branches:
      - master  # 监听 master 分支的 push 事件

permissions:
  contents: read
  id-token: write

jobs:
  build-and-publish:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]

    env:
      CIBW_BUILD: "cp310-*"
      CIBW_SKIP: "*-win32 *-manylinux_i686 *-musllinux* pp*"
      CIBW_BUILD_VERBOSITY: "1"

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"  # For running cibuildwheel

      - name: Install cibuildwheel
        run: pip install cibuildwheel==2.16.5

      - name: Build wheels (Python 3.10 only)
        run: |
          if [[ -z "$(find . -name '*.c' -o -name '*.cpp' -o -name '*.pyx')" ]]; then
            echo "Pure Python package detected, skipping cibuildwheel."
            python setup.py sdist bdist_wheel
          else
            cibuildwheel --output-dir dist
          fi

      - name: Publish to PyPI via Trusted Publisher
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages: dist/*
