jobs:
  build-and-publish:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install cibuildwheel
        run: pip install cibuildwheel

      - name: Build wheels
        env:
          CIBW_SKIP: "cp38-win32 cp39-win32 cp310-win32 pp*"
        run: cibuildwheel --output-dir dist

      - name: Publish to PyPI via Trusted Publisher
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages: dist/*